### ISSUE TITLE
JSON typo

### ISSUE THREAD

**Issue by RobyRemzy** [benawad/nextjs-persist-state-with-cookie#1]
Hi Ben,
there is probably a typo on the JSON.parse or somewhere else because the project give an error `SyntaxError: Unexpected token u in JSON at position 0`
I wish i could point it out here but i was not able to find it.
thanks!

**Comment by marcopollivier** [comment]
Hi, @benawad and @RobyRemzy 

I had the same problem and I think that fix solve it =)

**Comment by benawad** [comment]
@marcopollivier thanks for the @ I wasn't watching this repo for some reason so didn't get the notification until now. Just merged your pr, thanks
