### ISSUE TITLE
Nextjs file and folder structure 

### ISSUE THREAD

**Issue by lewatt23** [benawad/nextjs-persist-state-with-cookie#5]
Hi Ben!,
Sorry for writing here but please can you do a commit or do you have an advice on how to structure complex nextjs projects?, am about a to start a nextjs project in which there will be many interactions,  so am trying to see how to structure such projects since am next new bb. 

Thanks

**Comment by benawad** [comment]
https://github.com/benawad/destiny

**Comment by lewatt23** [comment]
Thanks!
